"""
Bluestock MF - Automated Weekly Performance Email
-------------------------------------------------
Sends a beautifully formatted HTML summary of the top 5 funds 
to stakeholders using standard SMTP.
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import pandas as pd
import os
from datetime import datetime

# --- CONFIGURATION ---
# Replace these with your actual credentials for testing
SENDER_EMAIL = "your_email@gmail.com" 
APP_PASSWORD = "your_16_char_app_password" 
RECEIVER_EMAIL = "target_recipient@example.com"

# Path Resolution
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SCORECARD_PATH = os.path.join(SCRIPT_DIR, "data", "processed", "fund_scorecard.csv")

def generate_html_table(df):
    """Converts a pandas dataframe into a styled HTML table."""
    html = """
    <table style="width: 100%; border-collapse: collapse; font-family: Arial, sans-serif; margin-top: 20px;">
        <thead>
            <tr style="background-color: #003366; color: white; text-align: left;">
                <th style="padding: 12px; border: 1px solid #ddd;">Rank</th>
                <th style="padding: 12px; border: 1px solid #ddd;">Scheme Name</th>
                <th style="padding: 12px; border: 1px solid #ddd;">3-Yr CAGR (%)</th>
                <th style="padding: 12px; border: 1px solid #ddd;">Sharpe Ratio</th>
            </tr>
        </thead>
        <tbody>
    """
    
    for index, row in df.iterrows():
        # Alternating row colors for readability
        bg_color = "#f2f2f2" if index % 2 == 0 else "#ffffff"
        html += f"""
            <tr style="background-color: {bg_color};">
                <td style="padding: 12px; border: 1px solid #ddd; text-align: center;"><b>{index + 1}</b></td>
                <td style="padding: 12px; border: 1px solid #ddd;">{row['scheme_name']}</td>
                <td style="padding: 12px; border: 1px solid #ddd; text-align: center; color: green;">{row['cagr_3yr_pct']:.2f}%</td>
                <td style="padding: 12px; border: 1px solid #ddd; text-align: center;">{row['sharpe_ratio']:.2f}</td>
            </tr>
        """
        
    html += "</tbody></table>"
    return html

def send_weekly_report():
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Preparing Weekly Performance Email...")
    
    try:
        # 1. Load Data
        df_scorecard = pd.read_csv(SCORECARD_PATH)
        
        # Sort and isolate the absolute top 5 funds by composite score
        df_top5 = df_scorecard.sort_values(by='composite_score', ascending=False).head(5).reset_index(drop=True)
        
        # 2. Build the HTML Email Envelope
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"📈 Bluestock Quant: Top 5 Elite Funds ({datetime.now().strftime('%b %d, %Y')})"
        msg["From"] = SENDER_EMAIL
        msg["To"] = RECEIVER_EMAIL
        
        html_content = f"""
        <html>
            <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
                <h2 style="color: #003366;">Weekly Quant Performance Summary</h2>
                <p>Hello Team,</p>
                <p>Please find the algorithmic performance rankings for the Bluestock Mutual Fund portfolio as of the latest market close. These funds currently exhibit the highest risk-adjusted efficiencies in our tracking universe.</p>
                
                {generate_html_table(df_top5)}
                
                <p style="margin-top: 30px; font-size: 12px; color: #777;">
                    <i>This is an automated report generated by the Bluestock Quant Pipeline. Do not reply to this email.</i>
                </p>
            </body>
        </html>
        """
        
        # Attach HTML payload
        msg.attach(MIMEText(html_content, "html"))
        
        # 3. Transmit via SMTP
        print("Connecting to SMTP server...")
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()  # Secure the connection
        server.login(SENDER_EMAIL, APP_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
        server.quit()
        
        print("✅ Email successfully transmitted!")
        
    except FileNotFoundError:
        print("❌ Error: Could not find fund_scorecard.csv. Ensure previous pipeline steps ran.")
    except Exception as e:
        print(f"❌ SMTP or Processing Error: {e}")

if __name__ == "__main__":
    send_weekly_report()